include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - annotate_overrides
    - avoid_empty_else
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_type_to_string
    - avoid_types_as_parameter_names
    - avoid_unnecessary_containers
    - cancel_subscriptions
    - close_sinks
    - collection_methods_unrelated_type
    - combinators_ordering
    - dangling_library_doc_comments
    - implicit_reopen
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - no_self_assignments
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_void_to_null
    - sort_child_properties_last
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_late
    - unnecessary_null_aware_assignments
    - unnecessary_statements
    - use_build_context_synchronously
    - use_key_in_widget_constructors

analyzer:
  errors:
    missing_return: error
    dead_code: warning
    avoid_print: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
